### ISSUE TITLE
goto('/app') returns Uncaught TypeError: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by andyBobro** [PaulMaly/svelte-pathfinder#1]
Method `goto` not works with relative paths, because it uses `new URL` which needs a second argument. I suggest adding checking for the count of arguments you pass and in the case with no second argument pass `window.location.href` as the second argument.

**Comment by PaulMaly** [comment]
@andyBobro Actually, `goto` not designed to work with relative paths, because there's not necessary to use it in this case. You can change any part of router state like this:

```javascript
$path = '/app'; // inside Svelte component
path.set('/app'); // outside of Svelte component
```
The purpose of `goto` helper is receive a full URL, split it to the URL parts and set that parts to appropriate stores.

**Comment by PaulMaly** [comment]
Looks like further discussion is not required. Closed.
